# Generated by Django 4.1.7 on 2023-04-19 18:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seeker_Profile',
            new_name='Provider_Profile',
        ),
    ]
