# Generated by Django 4.1.7 on 2023-04-19 18:23

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_api', '0002_rename_seeker_profile_provider_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seeker_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
                ('service', models.CharField(max_length=500)),
                ('interests', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), size=5)),
                ('goal', models.CharField(max_length=500)),
                ('similar_interest', models.BooleanField()),
                ('service_preference', models.CharField(max_length=500)),
                ('gender_preference', models.CharField(max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
